### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by tbraun96** [DPLYR-dev/SplashScreenFlutterPackage#65]
This library should be upgraded to be null-safe. I can fork a version, then we can do a PR if required

**Comment by edscodeblenders** [comment]
Please add null-safety support, so we can migrate our apps.

**Comment by keanallen** [comment]
Hello, any update about this?

**Comment by realkimmy** [comment]
```
splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
```
