### ISSUE TITLE
splashscreen dependency version missing

### ISSUE THREAD

**Issue by MerinAlex23** [DPLYR-dev/SplashScreenFlutterPackage#68]
**splashscreen dependency version missing**
In https://pub.dev/packages/splashscreen the splashscreen version is not mentioned as shown below.

```
dependencies:
    flutter:
      sdk: flutter
    splashscreen: 
```
**Expected behavior**
```
dependencies:
    flutter:
      sdk: flutter
    splashscreen: ^1.3.5
```
